### ISSUE TITLE
Base values and/or substitutions

### ISSUE THREAD

**Issue by markalfred** [markalfred/jeet-snippets#5]
Rather than `col` always inserting `column(1/{3})`, let user specify a base-value, so if 12 is used frequently, the snippet can insert `column(1/{12})`.

bonus points: emmet-style completion -- `w5<tab>` -> `width: 5px;`

**Comment by corysimmons** [comment]
Not sure how useful this would be but it definitely sounds cool.

What's the deal with the Emmet-style completion? That'd be amazing.

**Comment by markalfred** [comment]
I think it'd be nice if typing `col3/4<tab>` (or maybe `col3-4<tab>`, or even `col34<tab>`) would insert

``` scss
@mixin column(3/4);
```

Shorter-hand versions might assume the numerator to be 1, so `col3<tab>` could insert

``` scss
@mixin column(1/3);
```

...or something

**Comment by corysimmons** [comment]
Oh, yeah, that's definitely better. Nevermind. :dancer: 

I like the `col3/4` and `col3` syntaxes.

**Comment by markalfred** [comment]
May revisit this, but outside the project's scope currently

**Comment by corysimmons** [comment]
I think Jeet's being upgraded to be namespaced anyway, so `col3/4` would need to expand to `jeet-column(3/4)` or something.
