### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by verdond2** [markalfred/jeet-snippets#9]
I have Emmet installed and I can't seem to get this to work using scss. Have you experienced any conflict with Emmet?

**Comment by markalfred** [comment]
Works correctly for me with stock Emmet settings in SCSS with ST3, do you have any custom Emmet settings?

**Comment by verdond2** [comment]
I'm on sublime text 2, perhaps that could be the culprit? No custom settings setup.

**Comment by markalfred** [comment]
I'll take a look, thanks!

**Comment by verdond2** [comment]
Cheers Mark, appreciate it

**Comment by markalfred** [comment]
Haven't been able to reproduce with ST2. Are you using SCSS syntax highlighting? Does `Ctrl+Shift+P` show `source.scss` in the status bar, and if you type "alb", do you not see "alb --- align(both)" as a completion? Any other snippet packages that might be interfering?

**Comment by markalfred** [comment]
Closing this issue, feel free to re-open if these still aren't working
